# serverless.yml

service: my-express-application

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1

package:
  exclude:
    - src/**
    - .vscode
    - tsconfig.json
    - nodemon.json
  include: 
    - dist/**
    - package.json
    - package-lock.json
    - node_modules/**

functions:
  app:
    handler: dist/serverless.handler
    events:
      - http: 'ANY {proxy+}'

plugins:
  - serverless-offline
