# serverless.yml

service: elance-serverless-backend

custom:
  appTable: 'app-table-${self:provider.stage}'
  tokensTable: 'tokens-table-${self:provider.stage}'
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      migrate: true
      inMemory: true
      seed: true
      convertEmptyValues: true
    seed:
      test:
        sources:
          - table: 'app-table-${self:provider.stage}'
            sources: [test-data/app-table-dev.json]          

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["AppDynamoDBTable", "Arn" ] }
        - { "Fn::GetAtt": ["TokensDynamoDBTable", "Arn" ] }
  environment:
    APP_TABLE: ${self:custom.appTable}
    TOKENS_TABLE: ${self:custom.tokensTable}

package:
  exclude:
    - src/**
    - tsconfig.json
    - nodemon.json
    - test-data/**
    - .dynamodb/**
    - .circleci/**
    - README.md

functions:
  app:
    handler: dist/serverless.handler
    events:
      - http: 'ANY {proxy+}'

resources:
  Resources:
    AppDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: entity
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: entityIndex
            KeySchema:
              - AttributeName: entity
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        TableName: ${self:custom.appTable}
    TokensDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tokensTable}

plugins:
  - serverless-dynamodb-local
  - serverless-offline
