version: 2

defaults:
    working_directory: ~/repo

jobs:
  build:
    docker: 
      - image: circleci/node:8
    steps:
      - checkout
      - run:
        name: Update npm
        command: 'sudo npm install -g npm@latest'
      - restore-cache:
        name: Restoring Cache
        key: npm-dependency-cache-{{checksum "package.json"}}
      - run:
        name: Install node_modules
        command: 'sudo npm install'
      - save-cache:
        name: Saving node_modules cache
        key: npm-dependency-cache-{{checksum "package.json"}}
        paths: 
          - node_modules
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
        name: Restoring npm modules
        key: npm-dependency-cache-{{checksum "package.json"}}
      - run:
        name: Run unit tests
        command: 'npm run test'
  transpile:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
        name: Restoring npm modules
        key: npm-dependency-cache-{{checksum "package.json"}}    
      - run:
        name: Run local build
        command: 'sudo npm run build'
      - persist_to_workspace:
        root: ./
        paths:
          - dist
          - package.json
          - package-lock.json
  "merge to master":
    docker:
      - image: circleci/node:8
    steps:
      - run:
        name: Update git
        command: sudo apt install git
      - run:
        name: Add github as known_host
        command: |
          if [[ ! -d ~/.ssh ]]; then
            mkdir ~/.ssh
          fi
          if [[ ! -f ~/.ssh/known_hosts ]]; then
            touch ~/.ssh/known_hosts
          fi
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run:
        name: Clone master branch
        command: git clone https://www.github.com/pakdproject/linkedout-backend.git -b master backend
      - attach_workspace:
        at: ./backend
      # - run:
      #   name: Push changes
      #   command: |
      #     cd backend 
      #     git config credential.helper 'cache --timeout=120'
      #     git config --global user.email "ali9427@windowslive.com"
      #     git config --global user.name "alanj1998" &&  git config --global credential.helper cache
      #     git remote set-url origin https://alanj1998:$DEPLOY_GIT_TOKEN@github.com/pakdproject/linkedout-backend.git
      #     git add .
      #     git commit --allow-empty -m "merged from dev"
      #     git push -q origin master